##intergrate code for openai api. doc: https://python.langchain.com/docs/get_started/introduction/
# https://python.langchain.com/docs/get_started/quickstart/
import os 
from constants import openai_key

from langchain.llms import OpenAI

import streamlit as st

os.environ['OPENAI_API_KEY']= openai_key 


#intitializing streamlit framework

st.title("Langchain demowith OpenAI API")

#create textbox
input_text= st.text_input("Search any topic")

#OpenAI LLM model initialisation 

llm= OpenAI(temperature= 0.8)
#temp param of openai varies from 0 to 1. high 0.8 means it has more control n low 0.2 means it has focused 
#Temperature is a parameter that controls the “creativity” or randomness of the text generated by GPT-3. 
#A higher temperature (e.g., 0.7) results in more diverse and creative output, while a lower temperature (e.g., 0.2) makes the output more deterministic and focused.
# If I am using other search apis like google then I'd reduce the temp so that there will be the balance btw agent (openai) and googleresults

if input_text:
    st.write(llm(input_text)) # pass input_text into llm model described. then to print that use write() in streamlit
    